services:
  porch-server:
    image: "ghcr.io/wtsi-npg/python-3.14-npg-porch-3.0:latest"
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    healthcheck:
      test: curl -f http://127.0.0.1:8081
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      porch-server:
        condition: service_healthy
